# This configuration file defines labels to be applied based on modified paths
# in pull requests. Adjust the paths and labels according to your project needs.

# Apply labels based on the directories/files changed
labels:
  - name: rust
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

  - name: tests
    paths:
      - 'tests/**'

  - name: docs
    paths:
      - 'docs/**'
      - '*.md'

  - name: config
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/**'

  - name: build
    paths:
      - 'build/**'
      - 'scripts/**'
      - 'build.rs'