# This configuration file defines labels to be applied based on modified paths
# in pull requests. Adjust the paths and labels according to your project needs.

# Apply labels based on the directories/files changed
rust:
  - 'src/**'
  - 'Cargo.toml'
  - 'Cargo.lock'

tests:
  - 'tests/**'

documentation:
  - 'docs/**'
  - '*.md'

config:
  - 'Cargo.toml'
  - 'Cargo.lock'
  - '.github/**'

build:
  - 'build/**'
  - 'scripts/**'
  - 'build.rs'