# This configuration file defines labels to be applied based on modified paths
# in pull requests. Adjust the paths and labels according to your project needs.

# Apply labels based on the directories/files changed
rust:
  - name: rust
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

tests:
  - name: tests
    paths:
      - 'tests/**'

documentation:
  - name: documentation
    paths:
      - 'docs/**'
      - '*.md'

config:
  - name: config
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/**'

build:
  - name: build
    paths:
      - 'build/**'
      - 'scripts/**'
      - 'build.rs'