[package]
name = "genp"
version = "1.0.13"
description = "A simple Generator for PINs and Passwords"
authors = ["comboom.sucht","mcpeaps_HD"]
edition = "2021"

[dependencies]
clap = "4.5.16"
rand = "0.8.5"
