name: Genp - Build, Release, and Submit to Homebrew (with a twist!)

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          version=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$version" >> $GITHUB_ENV
      - id: create-release
        uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Genp v${{ env.version }} - Unlocking the Password Vault!
          changelog: |
            Hey there, folks! It's time to unleash the power of Genp v${{ env.version }} - the ultimate CLI tool for generating secure passwords and PINs that'll keep your data safer than a bank vault.

            With this release, we've added some extra spice to make things even more fun. Who needs boring old passwords when you can have funky fresh ones straight from the Genp factory?

            So, what are you waiting for? Grab your copy and start generating passwords that'll make your friends go "Whoa, how'd you come up with that?" 🎉

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            os-name: linux
            arch: x86_64
          - target: universal-apple-darwin
            os: macos-latest
            os-name: macos
            arch: universal
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            os-name: windows
            arch: x86_64
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            os-name: windows
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          version=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$version" >> $GITHUB_ENV
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: genp
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          archive: genp-v${{ env.version }}-${{ matrix.os-name }}-${{ matrix.arch }}
          token: ${{ secrets.GITHUB_TOKEN }}