name: Build, Release, and Submit to Homebrew

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags that match this pattern, e.g., v1.0.0

jobs:
  # Step 1: Create the release
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          version=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$version" >> $GITHUB_ENV

      - id: create-release
        uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # Step 2: Upload assets to the release
  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: universal-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: genp  # Replace with your actual binary name(s)
          target: ${{ matrix.target }}
          tar: unix  # Change as needed based on distribution preference
          zip: windows  # Change as needed based on distribution preference
          token: ${{ secrets.GITHUB_TOKEN }}

  # Step 3: Submit to Homebrew
  submit-formula:
    needs: upload-assets
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          version=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$version" >> $GITHUB_ENV

      - name: Submit to Homebrew
        run: |
          brew install -v --build-from-source --HEAD homebrew/core/genp
          brew create https://github.com/comboomPunkTsucht/genp/releases/download/${{ github.ref_name }}/genp-universal-apple-darwin.tar.gz --version=${{ env.version }}
          brew create https://github.com/comboomPunkTsucht/genp/releases/download/${{ github.ref_name }}/genp-x86_64-unknown-linux-gnu.tar.gz --version=${{ env.version }}
          brew install --interactive homebrew/core/genp
          brew audit --strict homebrew/core/genp
          brew pr-upload
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
