name: Build and Release Rust CLI

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger the workflow on tags that follow semantic versioning (e.g., v1.0.0)

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: create-release
        uses: taiki-e/create-gh-release-action@v1
        with:
          tag: ${{ github.ref }}  # GitHub ref is the tag name (e.g., refs/tags/v1.0.0)
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: universal-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: dino_cli_game  # Replace with your binary names
          target: ${{ matrix.target }}
          tar: unix  # Use 'all' if you want to distribute the tar.gz file on all platforms
          zip: windows  # Use 'all' if you want to distribute the zip file on all platforms
          token: ${{ secrets.GITHUB_TOKEN }}