name: Build and Release Rust CLI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: '1.70' # Setzen Sie hier die gewünschte Rust-Version ein

    - name: Build
      run: cargo build --release

    - name: Create Release
      id: create_release
      run: |
        VERSION=$(date +'%Y-%m-%d')
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

        # Install GitHub CLI
        sudo apt-get install gh

        # Create the release
        gh release create "${VERSION}" target/release/your_binary_name --title "Release ${VERSION}" --notes "Release created on ${VERSION}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}