name: Build and Release Rust CLI - 1

permissions:
  contents: write

on:
  push:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          version=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$version" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="v${{ env.version }}"
          title="v${{ env.version }}"
          description="created on $(date +%Y-%m-%d)"
          gh release create "$tag" --title "$title" --notes "$description"