name: Build and Release Rust CLI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable # Verwendet die neueste stabile Rust-Version
        components: rustfmt, clippy

    - name: Add targets for cross-compilation
      run: |
        rustup target add x86_64-unknown-linux-gnu
        rustup target add aarch64-unknown-linux-gnu
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-pc-windows-msvc
        rustup target add aarch64-pc-windows-msvc

    - name: Build for x86_64 Linux
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Build for aarch64 Linux
      run: cargo build --release --target aarch64-unknown-linux-gnu

    - name: Build for x86_64 macOS
      run: cargo build --release --target x86_64-apple-darwin

    - name: Build for aarch64 macOS
      run: cargo build --release --target aarch64-apple-darwin

    - name: Build for x86_64 Windows
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Build for aarch64 Windows
      run: cargo build --release --target aarch64-pc-windows-msvc

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dino_cli_game
        path: |
          target/x86_64-unknown-linux-gnu/release/dino_cli_game
          target/aarch64-unknown-linux-gnu/release/dino_cli_game
          target/x86_64-apple-darwin/release/dino_cli_game
          target/aarch64-apple-darwin/release/dino_cli_game
          target/x86_64-pc-windows-msvc/release/dino_cli_game.exe
          target/aarch64-pc-windows-msvc/release/dino_cli_game.exe

    - name: Create Release
      id: create_release
      run: |
        VERSION=$(date +'%Y-%m-%d')
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

        # Install GitHub CLI
        sudo apt-get install gh

        # Create the release
        gh release create "${VERSION}" \
          target/x86_64-unknown-linux-gnu/release/dino_cli_game \
          target/aarch64-unknown-linux-gnu/release/dino_cli_game \
          target/x86_64-apple-darwin/release/dino_cli_game \
          target/aarch64-apple-darwin/release/dino_cli_game \
          target/x86_64-pc-windows-msvc/release/dino_cli_game.exe \
          target/aarch64-pc-windows-msvc/release/dino_cli_game.exe \
          --title "Release ${VERSION}" \
          --notes "Release created on ${VERSION}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}