name: Build and Release Rust CLI - 1

permissions:
  contents: write

on:
  push:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          version=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$version" >> $GITHUB_ENV

      - name: Fetch all tags from remote
        run: |
          git fetch --tags

      - name: Delete existing tag if it exists locally and remotely
        run: |
          tag="v${{ env.version }}"
          if git show-ref --tags | grep -q "refs/tags/$tag"; then
            echo "Tag $tag exists locally, deleting..."
            git tag -d "$tag"
          else
            echo "Tag $tag does not exist locally."
          fi
          if git ls-remote --tags origin | grep -q "refs/tags/$tag"; then
            echo "Tag $tag exists remotely, deleting..."
            git push --delete origin "$tag"
          else
            echo "Tag $tag does not exist remotely."
          fi
          sleep 10

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="v${{ env.version }}"
          title="v${{ env.version }}"
          description="created on $(date +%Y-%m-%d)"
          git tag "$tag"
          git push origin "$tag"
          gh release create "$tag" --title "$title" --notes "$description"